### ISSUE TITLE
Unable to view log file while Lobster is running

### ISSUE THREAD

**Issue by apigram** [marshl/Lobster#123]
When I click on the 'View Log' menu option in the View menu, it attempts to open the lobster log file, but is unable to because the file is locked due to it being in use by Lobster.

Should this option be removed entirely or is this a bug regarding how the lobster.log file is opened?

**Comment by marshl** [comment]
@apigram This entirely depends on what program you use to open the log file. If you have Windows set up to open .log file with Notepad by default then you will encounter issues because Notepad requires and exclusive lock on the file. If you instead open .log files with a proper text editor such as Notepad++ (which doesn't need an exclusive lock) then there won't be a problem.

I could also change it so that the "View log"  link just opens the containing folder in explorer if you think that would be better.

**Comment by apigram** [comment]
Its actually set up to do so with WordPad, so I guess it does the same thing too.
